---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

data science:

I don't think there has been a single thing in this class that hasn't made me a better data scientist. Coming from my previous statistics courses where we are handed a set of clean data and told to plug and chug it through a programn or JMP to get results. I felt that this class gave me a lot of the tools to do a complete statistical analysis; before, I had the tools to analyse data, and now I have the tools to treat and manipulate data! I think the most important thing that I learned was how to clean data. For example, a lot of the functions from the dplyr package are very useful for taking data that is unorganized and many missing values and making it usable. I think the hip hop lyrics lab did a really good job at illustrating the power of these functions and skills. We were given a LOT of data with missing information and we were able to find meaningful information from it. The second most important take away I got from this class were the tools to do analysis. The ability to create graphs, tables, and summaries of data from nothing but a file and an IDE feels so good! The ggplot package has to be one of the most useful things a data scientists could use. It is so utilitarian! It allows you to create so many different types of plots as well as stylings to make them distinct and readible. I think lab 2 really shows off how many different things you can do with it. Part of doing analysis, is preparing the data to be modeled. Joins, pivots, and the lm function are some of the tools for maniputing dataframes to make them ready for either ggplot or a user to pull needed information. Lab 9 was really cool because it used all of these tools in it!
