---
title: "The Power of Efficiency"
format: html
editor: visual
---

power of efficiency:

The definition of efficient according to the American Heritage Dictionary is: "Causing less waste or requiring less effort than comparable devices or methods". In statistical computing, I think of efficiency in two ways, the effort put in by the person to do analysis compared to the computer and how fast the computer can execute the code. The first way I think of efficiency is comparing the effort it takes to clean, manipulate, and analyze data by hand, compared to doing it in R. I have realized too, in other statatistic classes, how powerful computers are for doing calculations. They complete things that would take humans FOREVER to do, like randomizing a study 1000s of times. This class took it a step further because not only do I have the tools that I learned in this class to make my statistical analysis a lot faster, I also learned how to look up almost anything I am unfamiliar with in R, if I need to accoplish a specific task. Next, at the beginning of the quarter, I remember thinking that writing efficient code (the second way I think about computing efficiency) was pretty useless. I figured that with the code we were writing it wouldn't matter because our computers are so powerful. Though, my thoughts on this have changed because of this quarter. Although it is true that writing efficient code won't make too much of a difference for the level I'm at, it is more important than that. It is also about building good habits and making sure your code is as efficient as possible. Vectorized function are what really made me appreciate the power of efficiency, because it not only takes less time to code it is also fast that looping through a vector, with functions I had known from before this class.
